### ISSUE TITLE
Example build not working. MissingRuleException

### ISSUE THREAD

**Issue by limh25** [nextstrain/seasonal-flu#112]
### Current Behavior

Cloned seasonal-flu repo, installed nextstrain cli with conda setup.
I tried to run the example build (nextstrain build . targets/flu_seasonal_h3n2_ha_12y), but it does not work, producing a "MissingRuleException."

Before the refactored workflow update, I was able to build with the same steps and example data.
I'd like to run the same with the updated, refactored workflow.

### How to reproduce
Steps to reproduce the current behavior:
1. Clone seasonal-flu repo
2. conda create -n nextstrain # python 3.9.12
3. Install NextStrain according to the documentation. `curl -fsSL --proto '=https' https://nextstrain.org/cli/installer/linux | bash; printf '\n%s\n' 'eval "$("/home/limh25/.nextstrain/cli-standalone/nextstrain" init-shell bash)"' >> ~/.bashrc; eval "$("/home/limh25/.nextstrain/cli-standalone/nextstrain" init-shell bash)"`
4. `python3 -m pip install nextstrain-cli; nextstrain setup conda; nextstrain setup --set-default conda`
5. Copy example data to data/
6. Run the example build. 
```nextstrain build . targets/flu_seasonal_h3n2_ha_12y --configfile /app/limh25/seasonal-flu/profiles/example/builds.yaml --cores 8 --printshellcmds --show-failed-logs --reason --verbose
(nextstrain) [limh25@machine1 seasonal-flu]$ nextstrain build . targets/flu_seasonal_h3n2_ha_12y --configfile /app/limh25/seasonal-flu/profiles/example/builds.yaml --cores 8 --printshellcmds --show-failed-logs --reason --verbose

Building DAG of jobs...
Full Traceback (most recent call last):
  File "/home/limh25/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/snakemake/__init__.py", line 771, in snakemake
    success = workflow.execute(
  File "/home/limh25/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/snakemake/workflow.py", line 741, in execute
    dag.init()
  File "/home/limh25/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/snakemake/dag.py", line 210, in init
    self.file2jobs(file),
  File "/home/limh25/.nextstrain/runtimes/conda/env/lib/python3.10/site-packages/snakemake/dag.py", line 1984, in file2jobs
    raise MissingRuleException(targetfile)
snakemake.exceptions.MissingRuleException: No rule to produce targets/flu_seasonal_h3n2_ha_12y (if you use input functions make sure that they don't raise unexpected exceptions).

MissingRuleException:
No rule to produce targets/flu_seasonal_h3n2_ha_12y (if you use input functions make sure that they don't raise unexpected exceptions).
unlocking
removed all locks
```

### Your environment: if running Nextstrain locally
 - Operating system: Amazon Linux 2
 - Version (nextstrain) [limh25@machine1 seasonal-flu]$ nextstrain version
nextstrain.cli 7.1.0, python 3.9.12
```
(nextstrain) [limh25@machine1 seasonal-flu]$ nextstrain check-setup
nextstrain-cli is up to date!

Testing your setup…

# docker is not supported
✘ no: docker is installed
✘ no: docker run works
? unknown: containers have access to >2 GiB of memory
✔ yes: image is new enough for this CLI version

# conda is supported
✔ yes: operating system is supported
✔ yes: runtime data dir doesn't have spaces
✔ yes: runtime appears set up
✔ yes: snakemake is installed and runnable
✔ yes: augur is installed and runnable
✔ yes: auspice is installed and runnable

# singularity is not supported
✘ no: singularity is installed
✘ no: singularity version None ≥ 3.0.0
✘ no: singularity works

# ambient is not supported
✘ no: snakemake is installed and runnable
✘ no: augur is installed and runnable
✘ no: auspice is installed and runnable

# aws-batch is not supported
✘ no: job description "nextstrain-job" exists
✘ no: job queue "nextstrain-job-queue" exists
✘ no: S3 bucket "nextstrain-jobs" exists

Supported Nextstrain runtimes: conda

All good!  Default runtime (conda) is supported.
```

There was no problem running the example build before the refactoring update. Now it does not work as expected.
Please help me running the example build.
Please also let me know if any further command-line outputs are needed to debug.

Thank you.

**Comment by joverlee521** [comment]
Hi @limh25, thank you for reporting this issue. 

You should be able to run the example build using the command:
```
nextstrain build .  --configfile profiles/ci/builds.yaml
```

I am updating the README to reflect this in #113.

**Comment by limh25** [comment]
Hi @joverlee521,
Thank you for your help. Now it runs, but produces error and stops. Error message below.

```
[Tue Jul 25 06:42:49 2023]
Job 16: Parsing fasta into sequences and metadata
Reason: Missing output files: data/h3n2/na.fasta, data/h3n2/metadata_na.tsv; Input files updated by another job: data/h3n2/raw_na.fasta


        augur parse             --sequences data/h3n2/raw_na.fasta             --output-sequences data/h3n2/na.fasta             --output-metadata data/h3n2/metadata_na.tsv             --fields strain virus accession date date_submitted region country division location passage_category originating_lab submitting_lab age gender             --prettify-fields region country division location originating_lab submitting_lab 2>&1 | tee logs/parse_h3n2_na.txt
        
[Tue Jul 25 06:42:49 2023]
Error in rule concat_titers_for_build:
    jobid: 20
    input: example_data/cdc_h3n2_cell_fra_titers.tsv
    output: builds/ci_build/all_titers.tsv
    log: logs/concat_titers_for_build_ci_build.txt (check log file(s) for error details)
    conda-env: /app/limh25/seasonal-flu/.snakemake/conda/bda388b1eaf328dc458bca193b400f10_
    shell:
        
        tsv-append -H example_data/cdc_h3n2_cell_fra_titers.tsv > builds/ci_build/all_titers.tsv 2> logs/concat_titers_for_build_ci_build.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job concat_titers_for_build since they might be corrupted:
builds/ci_build/all_titers.tsv
[Tue Jul 25 06:42:49 2023]
Error in rule build_reference_strains_table:
    jobid: 18
    input: config/h3n2/reference_strains.txt
    output: data/h3n2/reference_strains.tsv
    log: logs/build_reference_strains_table_h3n2.txt (check log file(s) for error details)
    conda-env: /app/limh25/seasonal-flu/.snakemake/conda/bda388b1eaf328dc458bca193b400f10_
    shell:
        
        csvtk add-header             --names strain             config/h3n2/reference_strains.txt             | csvtk uniq             | csvtk --out-tabs mutate2                 --name is_reference                 --expression "'True'" > data/h3n2/reference_strains.tsv
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job build_reference_strains_table since they might be corrupted:
data/h3n2/reference_strains.tsv
[Tue Jul 25 06:42:50 2023]
Finished job 10.
3 of 88 steps (3%) done
[Tue Jul 25 06:42:50 2023]
Finished job 16.
4 of 88 steps (5%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-07-25T064248.960339.snakemake.log
```

Should I turn off the titer part? If so, how am I supposed to run it without titer part?
Complete log file attached.

Thank you again.

[2023-07-25T064248.960339.snakemake.log](https://github.com/nextstrain/seasonal-flu/files/12160218/2023-07-25T064248.960339.snakemake.log)

**Comment by joverlee521** [comment]
@limh25 Could you provide the logs for the first rule that failed (`logs/concat_titers_for_build_ci_build.txt`)? It should contain more details on the error. 

Could you also provide the output of `nextstrain version --verbose`?

**Comment by limh25** [comment]
@joverlee521 The `logs/concat_titers_for_build_ci_build.txt` shows only one line `/usr/bin/bash: line 1: tsv-append: command not found`/

```
(nextstrain) [limh25@machine1 seasonal-flu]$ nextstrain version --verbose
nextstrain.cli 6.1.0.post1

Python
  /home/limh25/anaconda3/envs/nextstrain/bin/python3.7
  3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
  [GCC 9.4.0]

Runners
  docker 
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
    unknown

  conda 
    nextstrain-base unknown

  singularity 
    docker://nextstrain/base (not present)

  ambient (default)
    augur 18.1.2
    auspice 2.39.0

  aws-batch 
    unknown
```

Thanks.

**Comment by limh25** [comment]
@joverlee521 The example build works fine with `nextstrain build .  --configfile profiles/ci/builds.yaml`. I have two machines where nextstrain is installed, and the one with newer installation works fine. I just have to update the older one.

**Comment by joverlee521** [comment]
Glad to hear you were able to get it working!
